sudo: false
language: java
jdk:
  - oraclejdk8
addons:
  postgresql: '9.4'
services:
  - postgresql
  - mysql
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
install: ./gradlew assemble
script:
  - ./gradlew test
  - ./gradlew integrationTest
